reporter: apiary
custom:
  apiaryApiKey: b2e56e9d42811043be252968f850b5df
  apiaryApiName: nodeschoolhk
dry-run: null
hookfiles: '../dredd-hook.js'
sandbox: false
server: node index.js
server-wait: 3
init: false
names: false
only: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
blueprint: ../nodeschoolhk-apiary.apib
endpoint: 'http://localhost:3001'
